name: Gradle Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Give Gradle perms
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew clean build shadowJar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/libs/*.jar
          if-no-files-found: error
